using System;
using System.Collections.Generic;
using NUnit.Framework;
using ShooterMover.Application.Weapons.Execution;
using ShooterMover.Domain.Common;
using ShooterMover.Domain.Equipment;
using ShooterMover.Domain.Weapons.Catalog;
using ShooterMover.Domain.Weapons.Execution;

namespace ShooterMover.Tests.EditMode.Weapons.Execution
{
    public sealed partial class WeaponExecutionCoreTests
    {
        private static readonly StableId ActorStableId = StableId.Parse("actor.test-player");
        private static readonly StableId ParticipantStableId = StableId.Parse("participant.local-player");
        private static readonly StableId EquipmentDefinitionStableId = StableId.Parse("equipment.test-weapon");
        private static readonly StableId QualityStableId = StableId.Parse("quality.common");

        [Test] public void ExactEquipmentIdentity_IsForwardedIntoEveryEffect(){WeaponDefinitionData d=Definition("weapon.shotgun",7,18d,2d);EquipmentInstance i=Equipment("equipment-instance.shotgun-a");Harness h=HarnessFor(d,new[]{i});WeaponExecutionResult r=h.Core.TryExecute(Command(i,"fire.exact",0L));Assert.That(r.Status,Is.EqualTo(WeaponExecutionStatus.Accepted));Assert.That(h.Sink.Batches[0].EffectCount,Is.EqualTo(7));foreach(IWeaponEffectDescription e in h.Sink.Batches[0].Effects){Assert.That(e.Identity.EquipmentInstanceId.Value,Is.EqualTo(i.InstanceId));Assert.That(e.Identity.ParticipantId.Value,Is.EqualTo(ParticipantStableId));}}
        [Test] public void UnknownWeaponDefinition_FailsClosedWithoutFallback(){WeaponDefinitionData d=Definition("weapon.known",1,0d,5d);EquipmentInstance i=Equipment("equipment-instance.unknown");Harness h=HarnessFor(d,new[]{i},runtimeReferenceId:StableId.Parse("weapon.unknown"));Assert.That(h.Core.TryExecute(Command(i,"fire.unknown",0L)).Status,Is.EqualTo(WeaponExecutionStatus.UnknownWeaponDefinition));Assert.That(h.Sink.Batches,Is.Empty);}
        [Test] public void MissingEquippedEquipment_IsRejected(){WeaponDefinitionData d=Definition("weapon.rifle",1,0d,5d);EquipmentInstance i=Equipment("equipment-instance.missing");Harness h=HarnessFor(d,new EquipmentInstance[0]);Assert.That(h.Core.TryExecute(Command(i,"fire.missing",0L)).Status,Is.EqualTo(WeaponExecutionStatus.MissingEquippedEquipment));}
        [Test] public void InvalidAim_IsRejected(){WeaponDefinitionData d=Definition("weapon.rifle",1,0d,5d);EquipmentInstance i=Equipment("equipment-instance.invalid-aim");Harness h=HarnessFor(d,new[]{i});Assert.That(h.Core.TryExecute(Command(i,"fire.invalid-aim",0L,aim:new WeaponVector2(0d,0d))).Status,Is.EqualTo(WeaponExecutionStatus.InvalidCommand));Assert.That(h.Sink.Batches,Is.Empty);}
        [Test] public void PreviewOnlyDefinition_FailsClosed(){WeaponDefinitionData d=Definition("weapon.preview",1,0d,5d,availability:WeaponCatalogAvailability.PreviewOnly);EquipmentInstance i=Equipment("equipment-instance.preview");Harness h=HarnessFor(d,new[]{i});Assert.That(h.Core.TryExecute(Command(i,"fire.preview",0L)).Status,Is.EqualTo(WeaponExecutionStatus.PreviewOnlyWeaponDefinition));}
        [Test] public void UnsupportedEffect_FailsClosed(){WeaponDefinitionData d=Definition("weapon.dot",1,0d,5d,dotDps:2d);EquipmentInstance i=Equipment("equipment-instance.dot");Harness h=HarnessFor(d,new[]{i});Assert.That(h.Core.TryExecute(Command(i,"fire.dot",0L)).Status,Is.EqualTo(WeaponExecutionStatus.UnsupportedEffects));}
        [Test] public void InvalidTuning_FailsClosed(){WeaponDefinitionData d=Definition("weapon.invalid",1,0d,0d);EquipmentInstance i=Equipment("equipment-instance.invalid");Harness h=HarnessFor(d,new[]{i});Assert.That(h.Core.TryExecute(Command(i,"fire.invalid",0L)).Status,Is.EqualTo(WeaponExecutionStatus.InvalidTuning));}
        [Test] public void DeterministicSpread_RejectedRetryBuildsEquivalentBatch(){WeaponDefinitionData d=Definition("weapon.shotgun",7,24d,2d);EquipmentInstance i=Equipment("equipment-instance.deterministic");RecordingSink s=new RecordingSink{Reject=true};Harness h=HarnessFor(d,new[]{i},sink:s);WeaponFireCommand c=Command(i,"fire.deterministic",0L,seed:987654321UL);Assert.That(h.Core.TryExecute(c).Status,Is.EqualTo(WeaponExecutionStatus.SinkRejected));Assert.That(h.Core.TryExecute(c).Status,Is.EqualTo(WeaponExecutionStatus.SinkRejected));Assert.That(s.Batches[0].Fingerprint,Is.EqualTo(s.Batches[1].Fingerprint));}
        [Test] public void Shotgun_CountAndShotSequenceVaryDeterministically(){WeaponDefinitionData d=Definition("weapon.shotgun",7,24d,10d);EquipmentInstance i=Equipment("equipment-instance.sequence");Harness h=HarnessFor(d,new[]{i});Assert.That(h.Core.TryExecute(Command(i,"fire.sequence-a",0L,seed:42UL)).Succeeded,Is.True);Assert.That(h.Core.TryExecute(Command(i,"fire.sequence-b",10L,seed:42UL)).Succeeded,Is.True);Assert.That(h.Sink.Batches[0].EffectCount,Is.EqualTo(7));Assert.That(h.Sink.Batches[1].Identity.ShotSequence,Is.EqualTo(1L));Assert.That(h.Sink.Batches[0].Fingerprint,Is.Not.EqualTo(h.Sink.Batches[1].Fingerprint));}
        [Test] public void AtomicRejection_AllowsExactRetry(){WeaponDefinitionData d=Definition("weapon.shotgun",7,20d,2d);EquipmentInstance i=Equipment("equipment-instance.atomic-reject");RecordingSink s=new RecordingSink{Reject=true};Harness h=HarnessFor(d,new[]{i},sink:s);WeaponFireCommand c=Command(i,"fire.atomic-reject",0L);Assert.That(h.Core.TryExecute(c).Status,Is.EqualTo(WeaponExecutionStatus.SinkRejected));s.Reject=false;Assert.That(h.Core.TryExecute(c).Status,Is.EqualTo(WeaponExecutionStatus.Accepted));Assert.That(s.ValidatedCounts[0],Is.EqualTo(7));Assert.That(s.Batches[0].Fingerprint,Is.EqualTo(s.Batches[1].Fingerprint));}
        [Test] public void ExactReplayAfterAcceptance_DoesNotCallSinkTwice(){WeaponDefinitionData d=Definition("weapon.rifle",1,0d,5d);EquipmentInstance i=Equipment("equipment-instance.replay");Harness h=HarnessFor(d,new[]{i});WeaponFireCommand c=Command(i,"fire.replay",0L);Assert.That(h.Core.TryExecute(c).Succeeded,Is.True);Assert.That(h.Core.TryExecute(c).Status,Is.EqualTo(WeaponExecutionStatus.ReplayAccepted));Assert.That(h.Sink.Batches.Count,Is.EqualTo(1));}
        [Test] public void ConcreteEquipmentInstances_HaveIndependentCooldowns(){WeaponDefinitionData d=Definition("weapon.rifle",1,0d,1d);EquipmentInstance a=Equipment("equipment-instance.cooldown-a"),b=Equipment("equipment-instance.cooldown-b");Harness h=HarnessFor(d,new[]{a,b});Assert.That(h.Core.TryExecute(Command(a,"fire.cooldown-a",0L)).Succeeded,Is.True);Assert.That(h.Core.TryExecute(Command(b,"fire.cooldown-b",0L)).Succeeded,Is.True);Assert.That(h.Core.TryExecute(Command(a,"fire.cooldown-a-2",0L)).Status,Is.EqualTo(WeaponExecutionStatus.CooldownActive));}
        [Test] public void NewLifecycleGeneration_ResetsState(){WeaponDefinitionData d=Definition("weapon.shotgun",3,15d,1d);EquipmentInstance i=Equipment("equipment-instance.lifecycle");Harness h=HarnessFor(d,new[]{i});Assert.That(h.Core.TryExecute(Command(i,"fire.lifecycle",0L,generation:0L)).Succeeded,Is.True);Assert.That(h.Core.TryExecute(Command(i,"fire.lifecycle",0L,generation:1L)).Succeeded,Is.True);Assert.That(h.Sink.Batches[0].Identity.ShotSequence,Is.EqualTo(0L));Assert.That(h.Sink.Batches[1].Identity.ShotSequence,Is.EqualTo(0L));}
        [Test] public void ExplosiveProfile_ProducesExplosiveDescription(){WeaponDefinitionData d=Definition("weapon.rocket",1,0d,1d,areaDamage:12d,explosionRadius:3d);EquipmentInstance i=Equipment("equipment-instance.rocket");Harness h=HarnessFor(d,new[]{i});Assert.That(h.Core.TryExecute(Command(i,"fire.rocket",0L)).Succeeded,Is.True);Assert.That(h.Sink.Batches[0].Effects[0],Is.TypeOf<ExplosiveProjectileEffect>());}
        [Test] public void ChainProfile_ProducesChainRequest(){WeaponDefinitionData d=Definition("weapon.arc",1,0d,2d,chainTargets:4,chainRange:8d);EquipmentInstance i=Equipment("equipment-instance.arc");Harness h=HarnessFor(d,new[]{i});Assert.That(h.Core.TryExecute(Command(i,"fire.arc",0L)).Succeeded,Is.True);ChainArcEffect e=(ChainArcEffect)h.Sink.Batches[0].Effects[0];Assert.That(e.MaximumTargets,Is.EqualTo(4));}
        [Test] public void FifthBehavior_RegistersWithoutCoreModification(){WeaponDefinitionData d=Definition("weapon.test-burst",1,0d,5d);EquipmentInstance i=Equipment("equipment-instance.fifth");WeaponBehaviorId id=new WeaponBehaviorId(StableId.Parse("weapon-behavior.test-burst"));WeaponBehaviorRegistry registry=WeaponBehaviorRegistry.CreateWithBuiltIns();registry.Register(new ThreeProjectileTestBehavior(id));Harness h=HarnessFor(d,new[]{i},selector:new ExactDefinitionSelector("weapon.test-burst",id),registry:registry);Assert.That(h.Core.TryExecute(Command(i,"fire.fifth",0L)).EffectCount,Is.EqualTo(3));}
    }
}
