"use strict";

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { compileWeaponFolder } = require("./compile-weapon-folder.js");

const GENERATED_RELATIVE_PATH = path.join(
  "Assets",
  "ShooterMover",
  "Runtime",
  "Application",
  "Guns",
  "Catalog",
  "AuthoredGunCatalogue.Generated.cs"
);

function fail(message) {
  throw new Error(message);
}

function weaponFolders(root) {
  const base = path.join(root, "Content", "Weapons");
  if (!fs.existsSync(base)) fail(`Weapon content folder is missing: ${base}`);

  const folders = [];
  for (const category of fs.readdirSync(base, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .sort((left, right) => left.name.localeCompare(right.name))) {
    const categoryPath = path.join(base, category.name);
    for (const weapon of fs.readdirSync(categoryPath, { withFileTypes: true })
      .filter(entry => entry.isDirectory())
      .sort((left, right) => left.name.localeCompare(right.name))) {
      const folder = path.join(categoryPath, weapon.name);
      if (fs.existsSync(path.join(folder, "weapon.json"))) folders.push(folder);
    }
  }
  return folders;
}

function compileRuntimeCatalog(root) {
  const families = weaponFolders(root).map(folder => {
    const compiled = compileWeaponFolder(folder);
    const definitions = compiled.definitions
      .slice()
      .sort((left, right) => left.mark - right.mark)
      .map(definition => ({
        ...definition,
        definitionId: `${compiled.familyId}.mk${definition.mark}`
      }));

    if (definitions.length !== 3) {
      fail(`${compiled.familyId}: exactly three Marks are required.`);
    }
    const first = definitions[0];
    if (!first || !first.name || !first.rarity) {
      fail(`${compiled.familyId}: compiled name and rarity are required.`);
    }

    return {
      id: compiled.familyId,
      category: compiled.categoryFolder,
      name: first.name,
      rarity: first.rarity,
      marks: definitions
    };
  });

  if (!families.length) fail("No validated Weapon Maker families were found.");
  return {
    schema: 1,
    source: "Content/Weapons",
    families
  };
}

function generatedSource(catalog) {
  const json = JSON.stringify(catalog);
  const fingerprint = crypto.createHash("sha256").update(json).digest("hex");
  const definitionCount = catalog.families.reduce(
    (total, family) => total + family.marks.length,
    0
  );
  const verbatimJson = json.replace(/"/g, '""');

  return `namespace ShooterMover.Application.Guns.Catalog
{
    // Generated from validated Content/Weapons folders by tools/item-maker/runtime-export.js.
    // Do not edit this file by hand; edit the Weapon Maker JSON source instead.
    internal static class AuthoredGunCatalogueGenerated
    {
        public const int Schema = 1;
        public const int FamilyCount = ${catalog.families.length};
        public const int DefinitionCount = ${definitionCount};
        public const string SourceFingerprint = "sha256:${fingerprint}";
        public const string Json = @"${verbatimJson}";
    }
}
`;
}

function writeChanged(file, content) {
  if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === content) {
    return false;
  }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content, "utf8");
  return true;
}

function exportRuntimeCatalog(root) {
  const repositoryRoot = path.resolve(root);
  const catalog = compileRuntimeCatalog(repositoryRoot);
  const generatedFile = path.join(repositoryRoot, GENERATED_RELATIVE_PATH);
  const generatedChanged = writeChanged(
    generatedFile,
    generatedSource(catalog)
  );
  return {
    schema: catalog.schema,
    familyCount: catalog.families.length,
    definitionCount: catalog.families.reduce(
      (total, family) => total + family.marks.length,
      0
    ),
    generatedFile,
    generatedChanged
  };
}

function main() {
  const root = path.resolve(process.argv[2] || path.join(__dirname, "..", ".."));
  process.stdout.write(`${JSON.stringify(exportRuntimeCatalog(root), null, 2)}\n`);
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    const detail = String(error.stderr || error.stdout || error.message).trim();
    console.error(detail);
    process.exitCode = 1;
  }
}

module.exports = {
  GENERATED_RELATIVE_PATH,
  compileRuntimeCatalog,
  exportRuntimeCatalog
};
