using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ShooterMover.Domain.Common;
using ShooterMover.Domain.Rewards.Drops;
using ShooterMover.Domain.Rewards.Model;

namespace ShooterMover.Application.Rewards.Drops
{
    /// <summary>Production authored source profiles and aliases; aliases share one immutable profile object.</summary>
    public static class ProductionRewardSourceCatalogV1
    {
        public static readonly StableId SmallEnemyId=StableId.Parse("drop-source.small-enemy"), NormalEnemyId=StableId.Parse("drop-source.normal-enemy"), LargeEnemyId=StableId.Parse("drop-source.large-enemy"), BossEnemyId=StableId.Parse("drop-source.boss-enemy"), ExtraBossEnemyId=StableId.Parse("drop-source.extra-boss-enemy"), NormalPropId=StableId.Parse("drop-source.normal-prop"), RarePropId=StableId.Parse("drop-source.rare-prop"), ExtraRarePropId=StableId.Parse("drop-source.extra-rare-prop"), NormalHiddenTreasureId=StableId.Parse("drop-source.normal-hidden-treasure"), LargeHiddenLootId=StableId.Parse("drop-source.large-hidden-loot"), LargeTreasureLootId=StableId.Parse("drop-source.large-treasure-loot"), ExplicitNoDropId=StableId.Parse("drop-source.explicit-no-drop");
        private static readonly StableId MoneyId=StableId.Parse("currency.money"), ScrapId=StableId.Parse("currency.scrap");
        private static readonly RewardSourceProfileV1 SmallEnemyValue=BuildSmallEnemy(), NormalEnemyValue=BuildNormalEnemy(), LargeEnemyValue=BuildLargeEnemy(), BossEnemyValue=BuildBossEnemy(), ExtraBossEnemyValue=BuildExtraBossEnemy(), ExtraRarePropValue=BuildExtraRareProp(), LargeHiddenLootValue=BuildLargeHiddenLoot(), ExplicitNoDropValue=RewardSourceProfileV1.CreateExplicitNoDrop(ExplicitNoDropId);
        private static readonly ReadOnlyDictionary<StableId,RewardSourceProfileV1> ByReferenceId=BuildReferenceMap();
        private static readonly ReadOnlyDictionary<StableId,StableId> LegacyProfileMigration=BuildLegacyMigration();
        public static IReadOnlyDictionary<StableId,RewardSourceProfileV1> Profiles { get { return ByReferenceId; } }
        public static bool TryResolve(StableId referenceStableId,out RewardSourceProfileV1 profile) { return referenceStableId!=null&&ByReferenceId.TryGetValue(referenceStableId,out profile); }
        public static RewardSourceProfileV1 Get(StableId referenceStableId) { RewardSourceProfileV1 profile; if(!TryResolve(referenceStableId,out profile)) throw new KeyNotFoundException("Unknown production reward-source profile "+referenceStableId+"."); return profile; }
        public static bool TryMigrateLegacyProfileId(StableId legacyId,out StableId productionReferenceId) { return legacyId!=null&&LegacyProfileMigration.TryGetValue(legacyId,out productionReferenceId); }

        private static RewardSourceProfileV1 BuildSmallEnemy() { return RewardSourceProfileV1.Create(SmallEnemyId,ProductionStrongboxTierSelectionCatalogV1.LowSourceProfileId,new[]{ RewardRollGroupV1.CreateExclusive(StableId.Parse("drop-group.small-enemy.primary"),0,RewardBoxPacingModeV1.RandomBox,new[]{ RewardOutcomeV1.CreateExplicitNoDrop(StableId.Parse("drop-outcome.small-enemy.none"),850000), Outcome("small-enemy-money",RewardGrantKindV1.Money,MoneyId,1,3,135000), Outcome("small-enemy-scrap",RewardGrantKindV1.Scrap,ScrapId,1,1,14000), Outcome("small-enemy-box",RewardGrantKindV1.Strongbox,ProductionStrongboxTierSelectionCatalogV1.LowSourceProfileId,1,1,1000) })}); }
        private static RewardSourceProfileV1 BuildNormalEnemy() { return RewardSourceProfileV1.Create(NormalEnemyId,ProductionStrongboxTierSelectionCatalogV1.StandardSourceProfileId,new[]{ RewardRollGroupV1.CreateExclusive(StableId.Parse("drop-group.normal-enemy.primary"),0,RewardBoxPacingModeV1.RandomBox,new[]{ Outcome("normal-enemy-money",RewardGrantKindV1.Money,MoneyId,3,8,900000), Outcome("normal-enemy-scrap",RewardGrantKindV1.Scrap,ScrapId,1,2,80000), Outcome("normal-enemy-box",RewardGrantKindV1.Strongbox,ProductionStrongboxTierSelectionCatalogV1.StandardSourceProfileId,1,1,20000) })}); }
        private static RewardSourceProfileV1 BuildLargeEnemy() { return RewardSourceProfileV1.Create(LargeEnemyId,ProductionStrongboxTierSelectionCatalogV1.ImprovedSourceProfileId,new[]{ RewardRollGroupV1.CreateExclusive(StableId.Parse("drop-group.large-enemy.primary"),0,RewardBoxPacingModeV1.RandomBox,new[]{ Outcome("large-enemy-money",RewardGrantKindV1.Money,MoneyId,10,25,600000), Outcome("large-enemy-scrap",RewardGrantKindV1.Scrap,ScrapId,2,5,80000), Outcome("large-enemy-box",RewardGrantKindV1.Strongbox,ProductionStrongboxTierSelectionCatalogV1.ImprovedSourceProfileId,1,1,320000) })}); }
        private static RewardSourceProfileV1 BuildBossEnemy() { return RewardSourceProfileV1.Create(BossEnemyId,ProductionStrongboxTierSelectionCatalogV1.BossSourceProfileId,new[]{ RewardRollGroupV1.CreateGuaranteed(StableId.Parse("drop-group.boss.box"),0,RewardBoxPacingModeV1.GuaranteedBox,new[]{Outcome("boss-box",RewardGrantKindV1.Strongbox,ProductionStrongboxTierSelectionCatalogV1.BossSourceProfileId,1,1,1)}), RewardRollGroupV1.CreateGuaranteed(StableId.Parse("drop-group.boss.money"),1,RewardBoxPacingModeV1.None,new[]{Outcome("boss-money",RewardGrantKindV1.Money,MoneyId,25,50,1)})}); }
        private static RewardSourceProfileV1 BuildExtraBossEnemy() { return RewardSourceProfileV1.Create(ExtraBossEnemyId,ProductionStrongboxTierSelectionCatalogV1.TreasureSourceProfileId,new[]{ RewardRollGroupV1.CreateGuaranteed(StableId.Parse("drop-group.extra-boss.money"),0,RewardBoxPacingModeV1.None,new[]{Outcome("extra-boss-money",RewardGrantKindV1.Money,MoneyId,50,100,1)}), RewardRollGroupV1.CreateWeightedCount(StableId.Parse("drop-group.extra-boss.box-count"),1,RewardBoxPacingModeV1.GuaranteedBox,new[]{ Outcome("extra-boss-box-3",RewardGrantKindV1.Strongbox,ProductionStrongboxTierSelectionCatalogV1.TreasureSourceProfileId,3,3,70), Outcome("extra-boss-box-4",RewardGrantKindV1.Strongbox,ProductionStrongboxTierSelectionCatalogV1.TreasureSourceProfileId,4,4,25), Outcome("extra-boss-box-5",RewardGrantKindV1.Strongbox,ProductionStrongboxTierSelectionCatalogV1.TreasureSourceProfileId,5,5,5) })}); }
        private static RewardSourceProfileV1 BuildExtraRareProp() { return RewardSourceProfileV1.Create(ExtraRarePropId,ProductionStrongboxTierSelectionCatalogV1.TreasureSourceProfileId,new[]{ RewardRollGroupV1.CreateWeightedCount(StableId.Parse("drop-group.extra-rare-prop.box-count"),0,RewardBoxPacingModeV1.GuaranteedBox,new[]{ Outcome("extra-rare-prop-box-2",RewardGrantKindV1.Strongbox,ProductionStrongboxTierSelectionCatalogV1.TreasureSourceProfileId,2,2,70), Outcome("extra-rare-prop-box-3",RewardGrantKindV1.Strongbox,ProductionStrongboxTierSelectionCatalogV1.TreasureSourceProfileId,3,3,25), Outcome("extra-rare-prop-box-4",RewardGrantKindV1.Strongbox,ProductionStrongboxTierSelectionCatalogV1.TreasureSourceProfileId,4,4,5) })}); }
        private static RewardSourceProfileV1 BuildLargeHiddenLoot() { return RewardSourceProfileV1.Create(LargeHiddenLootId,ProductionStrongboxTierSelectionCatalogV1.TreasureSourceProfileId,new[]{ RewardRollGroupV1.CreateGuaranteed(StableId.Parse("drop-group.large-hidden-loot.box"),0,RewardBoxPacingModeV1.GuaranteedBox,new[]{Outcome("large-hidden-loot-box",RewardGrantKindV1.Strongbox,ProductionStrongboxTierSelectionCatalogV1.TreasureSourceProfileId,1,1,1)})}); }
        private static RewardOutcomeV1 Outcome(string slug,RewardGrantKindV1 kind,StableId content,long minimum,long maximum,ulong weight) { return RewardOutcomeV1.CreateGrant(StableId.Create("drop-outcome",slug),RewardGrantSpecificationV1.Create(StableId.Create("drop-grant",slug),kind,content,RewardQuantityRangeV1.Create(minimum,maximum),Array.Empty<RewardScalingInputDescriptorV1>()),weight); }
        private static ReadOnlyDictionary<StableId,RewardSourceProfileV1> BuildReferenceMap() { return new ReadOnlyDictionary<StableId,RewardSourceProfileV1>(new Dictionary<StableId,RewardSourceProfileV1>{{SmallEnemyId,SmallEnemyValue},{NormalEnemyId,NormalEnemyValue},{LargeEnemyId,LargeEnemyValue},{BossEnemyId,BossEnemyValue},{ExtraBossEnemyId,ExtraBossEnemyValue},{NormalPropId,NormalEnemyValue},{RarePropId,LargeEnemyValue},{ExtraRarePropId,ExtraRarePropValue},{NormalHiddenTreasureId,NormalEnemyValue},{LargeHiddenLootId,LargeHiddenLootValue},{LargeTreasureLootId,ExtraRarePropValue},{ExplicitNoDropId,ExplicitNoDropValue}}); }
        private static ReadOnlyDictionary<StableId,StableId> BuildLegacyMigration() { return new ReadOnlyDictionary<StableId,StableId>(new Dictionary<StableId,StableId>{{StableId.Parse("drop.enemy-common"),NormalEnemyId},{StableId.Parse("drop.enemy-turret"),LargeEnemyId},{StableId.Parse("drop.enemy-none"),ExplicitNoDropId},{StableId.Parse("drop.prop-stage1-ordinary"),NormalPropId},{StableId.Parse("drop.prop-stage1-explosive"),RarePropId},{StableId.Parse("drop.prop-legacy-none"),ExplicitNoDropId}}); }
    }
}
