using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ShooterMover.Domain.Common;
using ShooterMover.Domain.Rewards.Drops;
using ShooterMover.Domain.Rewards.Model;

namespace ShooterMover.Application.Rewards.Drops
{
    /// <summary>Production authored source profiles and aliases; aliases share one immutable profile object.</summary>
    public static class RewardSourceCatalog
    {
        public static readonly StableId SmallEnemyId=StableId.Parse("drop-source.small-enemy"), NormalEnemyId=StableId.Parse("drop-source.normal-enemy"), LargeEnemyId=StableId.Parse("drop-source.large-enemy"), BossEnemyId=StableId.Parse("drop-source.boss-enemy"), ExtraBossEnemyId=StableId.Parse("drop-source.extra-boss-enemy"), NormalPropId=StableId.Parse("drop-source.normal-prop"), RarePropId=StableId.Parse("drop-source.rare-prop"), ExtraRarePropId=StableId.Parse("drop-source.extra-rare-prop"), NormalHiddenTreasureId=StableId.Parse("drop-source.normal-hidden-treasure"), LargeHiddenLootId=StableId.Parse("drop-source.large-hidden-loot"), LargeTreasureLootId=StableId.Parse("drop-source.large-treasure-loot"), ExplicitNoDropId=StableId.Parse("drop-source.explicit-no-drop");
        private static readonly StableId MoneyId=StableId.Parse("currency.money"), ScrapId=StableId.Parse("currency.scrap");
        private static readonly RewardSourceProfile SmallEnemyValue=BuildSmallEnemy(), NormalEnemyValue=BuildNormalEnemy(), LargeEnemyValue=BuildLargeEnemy(), BossEnemyValue=BuildBossEnemy(), ExtraBossEnemyValue=BuildExtraBossEnemy(), ExtraRarePropValue=BuildExtraRareProp(), LargeHiddenLootValue=BuildLargeHiddenLoot(), ExplicitNoDropValue=RewardSourceProfile.CreateExplicitNoDrop(ExplicitNoDropId);
        private static readonly ReadOnlyDictionary<StableId,RewardSourceProfile> ByReferenceId=BuildReferenceMap();
        private static readonly ReadOnlyDictionary<StableId,StableId> LegacyProfileMigration=BuildLegacyMigration();
        public static IReadOnlyDictionary<StableId,RewardSourceProfile> Profiles { get { return ByReferenceId; } }
        public static bool TryResolve(StableId referenceStableId,out RewardSourceProfile profile) { profile = null; return referenceStableId!=null&&ByReferenceId.TryGetValue(referenceStableId,out profile); }
        public static RewardSourceProfile Get(StableId referenceStableId) { RewardSourceProfile profile; if(!TryResolve(referenceStableId,out profile)) throw new KeyNotFoundException("Unknown production reward-source profile "+referenceStableId+"."); return profile; }
        public static bool TryMigrateLegacyProfileId(StableId legacyId,out StableId productionReferenceId) { productionReferenceId = null; return legacyId!=null&&LegacyProfileMigration.TryGetValue(legacyId,out productionReferenceId); }

        private static RewardSourceProfile BuildSmallEnemy() { return RewardSourceProfile.Create(SmallEnemyId,StrongboxTierSelectionCatalog.LowSourceProfileId,new[]{ RewardRollGroup.CreateExclusive(StableId.Parse("drop-group.small-enemy.primary"),0,RewardBoxPacingMode.RandomBox,new[]{ RewardOutcome.CreateExplicitNoDrop(StableId.Parse("drop-outcome.small-enemy.none"),850000), Outcome("small-enemy-money",RewardGrantKind.Money,MoneyId,1,3,135000), Outcome("small-enemy-scrap",RewardGrantKind.Scrap,ScrapId,1,1,14000), Outcome("small-enemy-box",RewardGrantKind.Strongbox,StrongboxTierSelectionCatalog.LowSourceProfileId,1,1,1000) })}); }
        private static RewardSourceProfile BuildNormalEnemy() { return RewardSourceProfile.Create(NormalEnemyId,StrongboxTierSelectionCatalog.StandardSourceProfileId,new[]{ RewardRollGroup.CreateExclusive(StableId.Parse("drop-group.normal-enemy.primary"),0,RewardBoxPacingMode.RandomBox,new[]{ Outcome("normal-enemy-money",RewardGrantKind.Money,MoneyId,3,8,900000), Outcome("normal-enemy-scrap",RewardGrantKind.Scrap,ScrapId,1,2,80000), Outcome("normal-enemy-box",RewardGrantKind.Strongbox,StrongboxTierSelectionCatalog.StandardSourceProfileId,1,1,20000) })}); }
        private static RewardSourceProfile BuildLargeEnemy() { return RewardSourceProfile.Create(LargeEnemyId,StrongboxTierSelectionCatalog.ImprovedSourceProfileId,new[]{ RewardRollGroup.CreateExclusive(StableId.Parse("drop-group.large-enemy.primary"),0,RewardBoxPacingMode.RandomBox,new[]{ Outcome("large-enemy-money",RewardGrantKind.Money,MoneyId,10,25,600000), Outcome("large-enemy-scrap",RewardGrantKind.Scrap,ScrapId,2,5,80000), Outcome("large-enemy-box",RewardGrantKind.Strongbox,StrongboxTierSelectionCatalog.ImprovedSourceProfileId,1,1,320000) })}); }
        private static RewardSourceProfile BuildBossEnemy() { return RewardSourceProfile.Create(BossEnemyId,StrongboxTierSelectionCatalog.BossSourceProfileId,new[]{ RewardRollGroup.CreateGuaranteed(StableId.Parse("drop-group.boss.box"),0,RewardBoxPacingMode.GuaranteedBox,new[]{Outcome("boss-box",RewardGrantKind.Strongbox,StrongboxTierSelectionCatalog.BossSourceProfileId,1,1,1)}), RewardRollGroup.CreateGuaranteed(StableId.Parse("drop-group.boss.money"),1,RewardBoxPacingMode.None,new[]{Outcome("boss-money",RewardGrantKind.Money,MoneyId,25,50,1)})}); }
        private static RewardSourceProfile BuildExtraBossEnemy() { return RewardSourceProfile.Create(ExtraBossEnemyId,StrongboxTierSelectionCatalog.TreasureSourceProfileId,new[]{ RewardRollGroup.CreateGuaranteed(StableId.Parse("drop-group.extra-boss.money"),0,RewardBoxPacingMode.None,new[]{Outcome("extra-boss-money",RewardGrantKind.Money,MoneyId,50,100,1)}), RewardRollGroup.CreateWeightedCount(StableId.Parse("drop-group.extra-boss.box-count"),1,RewardBoxPacingMode.GuaranteedBox,new[]{ Outcome("extra-boss-box-3",RewardGrantKind.Strongbox,StrongboxTierSelectionCatalog.TreasureSourceProfileId,3,3,70), Outcome("extra-boss-box-4",RewardGrantKind.Strongbox,StrongboxTierSelectionCatalog.TreasureSourceProfileId,4,4,25), Outcome("extra-boss-box-5",RewardGrantKind.Strongbox,StrongboxTierSelectionCatalog.TreasureSourceProfileId,5,5,5) })}); }
        private static RewardSourceProfile BuildExtraRareProp() { return RewardSourceProfile.Create(ExtraRarePropId,StrongboxTierSelectionCatalog.TreasureSourceProfileId,new[]{ RewardRollGroup.CreateWeightedCount(StableId.Parse("drop-group.extra-rare-prop.box-count"),0,RewardBoxPacingMode.GuaranteedBox,new[]{ Outcome("extra-rare-prop-box-2",RewardGrantKind.Strongbox,StrongboxTierSelectionCatalog.TreasureSourceProfileId,2,2,70), Outcome("extra-rare-prop-box-3",RewardGrantKind.Strongbox,StrongboxTierSelectionCatalog.TreasureSourceProfileId,3,3,25), Outcome("extra-rare-prop-box-4",RewardGrantKind.Strongbox,StrongboxTierSelectionCatalog.TreasureSourceProfileId,4,4,5) })}); }
        private static RewardSourceProfile BuildLargeHiddenLoot() { return RewardSourceProfile.Create(LargeHiddenLootId,StrongboxTierSelectionCatalog.TreasureSourceProfileId,new[]{ RewardRollGroup.CreateGuaranteed(StableId.Parse("drop-group.large-hidden-loot.box"),0,RewardBoxPacingMode.GuaranteedBox,new[]{Outcome("large-hidden-loot-box",RewardGrantKind.Strongbox,StrongboxTierSelectionCatalog.TreasureSourceProfileId,1,1,1)})}); }
        private static RewardOutcome Outcome(string slug,RewardGrantKind kind,StableId content,long minimum,long maximum,ulong weight) { return RewardOutcome.CreateGrant(StableId.Create("drop-outcome",slug),RewardGrantSpecification.Create(StableId.Create("drop-grant",slug),kind,content,RewardQuantityRange.Create(minimum,maximum),Array.Empty<RewardScalingInputDescriptor>()),weight); }
        private static ReadOnlyDictionary<StableId,RewardSourceProfile> BuildReferenceMap() { return new ReadOnlyDictionary<StableId,RewardSourceProfile>(new Dictionary<StableId,RewardSourceProfile>{{SmallEnemyId,SmallEnemyValue},{NormalEnemyId,NormalEnemyValue},{LargeEnemyId,LargeEnemyValue},{BossEnemyId,BossEnemyValue},{ExtraBossEnemyId,ExtraBossEnemyValue},{NormalPropId,NormalEnemyValue},{RarePropId,LargeEnemyValue},{ExtraRarePropId,ExtraRarePropValue},{NormalHiddenTreasureId,NormalEnemyValue},{LargeHiddenLootId,LargeHiddenLootValue},{LargeTreasureLootId,ExtraRarePropValue},{ExplicitNoDropId,ExplicitNoDropValue}}); }
        private static ReadOnlyDictionary<StableId,StableId> BuildLegacyMigration() { return new ReadOnlyDictionary<StableId,StableId>(new Dictionary<StableId,StableId>{{StableId.Parse("drop.enemy-common"),NormalEnemyId},{StableId.Parse("drop.enemy-turret"),LargeEnemyId},{StableId.Parse("drop.enemy-none"),ExplicitNoDropId},{StableId.Parse("drop.prop-stage1-ordinary"),NormalPropId},{StableId.Parse("drop.prop-stage1-explosive"),RarePropId},{StableId.Parse("drop.prop-legacy-none"),ExplicitNoDropId}}); }
    }
}
