"use strict";
(() => {
 const css=document.createElement("link");css.rel="stylesheet";css.href="style-editor-speed.css";document.head.appendChild(css);
 const key="shooter-mover.level-maker.view.v1",defaults={labels:true,grid:true,enemies:true,props:true,doors:true,spawn:true};let view={...defaults};try{view={...view,...JSON.parse(localStorage.getItem(key)||"null")}}catch{}
 const baseRender=renderCanvas,baseGrid=drawGrid;
 function save(){try{localStorage.setItem(key,JSON.stringify(view))}catch{}}
 drawGrid=function(r){if(view.grid)return baseGrid(r);ctx.fillStyle="#0d1015";ctx.fillRect(0,0,r.width,r.height)};
 function filtered(draw){const rooms=state.rooms.map(r=>({r,e:r.entities,d:r.doors,s:r.playerStart})),fill=ctx.fillText;try{for(const x of rooms){x.r.entities=x.e.filter(e=>e.kind==="enemy"?view.enemies:view.props);if(!view.doors)x.r.doors=[];if(!view.spawn)x.r.playerStart=null}if(!view.labels)ctx.fillText=()=>{};draw()}finally{ctx.fillText=fill;for(const x of rooms){x.r.entities=x.e;x.r.doors=x.d;x.r.playerStart=x.s}}}
 function footprint(o){const a=state.catalog.find(x=>x.id===o?.object),m=`${a?.id||o?.object||""} ${a?.label||""}`.match(/(\d+)\s*[x×]\s*(\d+)/i);return m?{w:+m[1],h:+m[2]}:{w:1,h:1}}
 function outline(){if(state.editor.viewMode!=="room")return;const s=selected(),o=s?.entity||s?.door;if(!o)return;if(o.kind==="door"&&!view.doors||o.kind==="enemy"&&!view.enemies||o.kind!=="door"&&o.kind!=="enemy"&&!view.props)return;ctx.save();ctx.strokeStyle="#fff";ctx.fillStyle="rgba(121,201,255,.08)";ctx.lineWidth=3;ctx.setLineDash([7,4]);if(o.kind==="door"){const p=worldToScreen(o.position),w=1.72*state.editor.zoom,h=.55*state.editor.zoom;ctx.translate(p[0],p[1]);ctx.rotate(-deg2rad(o.rotation||0));ctx.fillRect(-w/2,-h/2,w,h);ctx.strokeRect(-w/2,-h/2,w,h);ctx.restore();return}const f=o.kind==="enemy"||o.kind==="teleporter"?{w:1,h:1}:footprint(o),a=worldToScreen([o.position[0]-f.w/2,o.position[1]+f.h/2]),b=worldToScreen([o.position[0]+f.w/2,o.position[1]-f.h/2]),x=Math.min(a[0],b[0]),y=Math.min(a[1],b[1]),w=Math.abs(b[0]-a[0]),h=Math.abs(b[1]-a[1]);ctx.fillRect(x+2,y+2,w-4,h-4);ctx.strokeRect(x+1.5,y+1.5,w-3,h-3);ctx.restore()}
 renderCanvas=function(){filtered(baseRender);outline()};
 function install(){const controls=document.querySelector("#room-focus-tools");if(!controls||document.querySelector("#toggleViewMenu"))return;const button=document.createElement("button");button.id="toggleViewMenu";button.textContent="View";const anchor=document.querySelector("#toggleToolsPopover")||document.querySelector("#toggleAssetsDrawer");anchor?.after(button);const menu=document.createElement("div");menu.id="viewMenu";menu.className="floating view-menu";menu.innerHTML=`<b>View</b>${[["labels","Labels"],["grid","Background grid"],["enemies","Enemies"],["props","Props & walls"],["doors","Doors & connections"],["spawn","Spawn"]].map(([k,l])=>`<label><input type="checkbox" data-k="${k}"> ${l}</label>`).join("")}<button data-all>Show all</button>`;document.querySelector("#stage-wrap")?.appendChild(menu);const sync=()=>menu.querySelectorAll("[data-k]").forEach(i=>i.checked=!!view[i.dataset.k]);button.onclick=e=>{e.stopPropagation();document.body.classList.toggle("view-menu-open");sync()};menu.onclick=e=>e.stopPropagation();menu.querySelectorAll("[data-k]").forEach(i=>i.onchange=()=>{view[i.dataset.k]=i.checked;save();renderCanvas()});menu.querySelector("[data-all]").onclick=()=>{view={...defaults};save();sync();renderCanvas()};document.addEventListener("click",()=>document.body.classList.remove("view-menu-open"));sync()}
 install();
})();
