// <auto-generated />
// Source: d30030776909a42fed4633c49817c29b8c2eddf2:Assets/ShooterMover/Resources/WeaponCatalog/weapon_baseline_v01.json
using System;
using ShooterMover.Domain.Common;
using ShooterMover.Domain.Guns;
using ShooterMover.Domain.Guns.Execution;

namespace ShooterMover.Application.Guns.Catalog
{
    public static partial class GunCatalogue
    {
        private static GunFamily[] BuildPr288Families()
        {
            return new[]
            {
                BuildPr288Family(
                    "shotgun",
                    "Shotgun",
                    "shotgun",
                    "common",
                    "shotgun-physical",
                    new[]
                    {
                        new Pr288MarkSource(
                            1, 5,
                            FireSettings.SemiAutomatic(1.45d),
                            GunShotPattern.Canonical(7, 19d),
                            1.552015862068966d,
                            GunDamageCategory.Physical,
                            0, 0.48d,
                            16d, 25d, 0.1d),
                        new Pr288MarkSource(
                            2, 28,
                            FireSettings.SemiAutomatic(1.4935d),
                            GunShotPattern.Canonical(7, 18.05d),
                            5.679319833641276d,
                            GunDamageCategory.Physical,
                            0, 0.5184d,
                            16.48d, 26.25d, 0.1d),
                        new Pr288MarkSource(
                            3, 52,
                            FireSettings.SemiAutomatic(1.537d),
                            GunShotPattern.Canonical(7, 17.1d),
                            16.10189087332782d,
                            GunDamageCategory.Physical,
                            1, 0.5568d,
                            16.96d, 27.500000000000004d, 0.1d)
                    }),
                BuildPr288Family(
                    "sniper",
                    "Sniper",
                    "normal-firearm",
                    "rare",
                    "normal-physical",
                    new[]
                    {
                        new Pr288MarkSource(
                            1, 14,
                            FireSettings.SemiAutomatic(0.72d),
                            GunShotPattern.Canonical(1, 0.15d),
                            37.436299190750226d,
                            GunDamageCategory.Physical,
                            2, 0.75d,
                            58d, 75d, 0.1d),
                        new Pr288MarkSource(
                            2, 38,
                            FireSettings.SemiAutomatic(0.7416d),
                            GunShotPattern.Canonical(1, 0.1425d),
                            153.73283204605988d,
                            GunDamageCategory.Physical,
                            2, 0.81d,
                            59.74d, 78.75d, 0.1d),
                        new Pr288MarkSource(
                            3, 62,
                            FireSettings.SemiAutomatic(0.7632d),
                            GunShotPattern.Canonical(1, 0.135d),
                            435.8601659639591d,
                            GunDamageCategory.Physical,
                            3, 0.8699999999999999d,
                            61.480000000000004d, 82.5d, 0.1d)
                    }),
                BuildPr288Family(
                    "fast_sniper",
                    "Fast Sniper",
                    "normal-firearm",
                    "rare",
                    "normal-physical",
                    new[]
                    {
                        new Pr288MarkSource(
                            1, 25,
                            FireSettings.SemiAutomatic(2.15d),
                            GunShotPattern.Canonical(1, 0.35d),
                            27.516298357012836d,
                            GunDamageCategory.Physical,
                            1, 0.48d,
                            48d, 82d, 0.1d),
                        new Pr288MarkSource(
                            2, 49,
                            FireSettings.SemiAutomatic(2.2145d),
                            GunShotPattern.Canonical(1, 0.33249999999999996d),
                            77.94746179113703d,
                            GunDamageCategory.Physical,
                            1, 0.5184d,
                            49.44d, 86.10000000000001d, 0.1d),
                        new Pr288MarkSource(
                            3, 73,
                            FireSettings.SemiAutomatic(2.279d),
                            GunShotPattern.Canonical(1, 0.315d),
                            224.1520663645046d,
                            GunDamageCategory.Physical,
                            2, 0.5568d,
                            50.88d, 90.2d, 0.1d)
                    }),
                BuildPr288Family(
                    "heavy_gatling",
                    "Heavy Gatling Gun",
                    "normal-firearm",
                    "rare",
                    "normal-physical",
                    new[]
                    {
                        new Pr288MarkSource(
                            1, 34,
                            FireSettings.Automatic(14d),
                            GunShotPattern.Canonical(1, 2.5d),
                            8.9882925089946d,
                            GunDamageCategory.Physical,
                            1, 0.62d,
                            36d, 42d, 0.1d),
                        new Pr288MarkSource(
                            2, 57,
                            FireSettings.Automatic(14.42d),
                            GunShotPattern.Canonical(1, 2.375d),
                            24.134411076114308d,
                            GunDamageCategory.Physical,
                            1, 0.6696000000000001d,
                            37.08d, 44.1d, 0.1d),
                        new Pr288MarkSource(
                            3, 81,
                            FireSettings.Automatic(14.84d),
                            GunShotPattern.Canonical(1, 2.25d),
                            72.07833065445672d,
                            GunDamageCategory.Physical,
                            2, 0.7192d,
                            38.160000000000004d, 46.2d, 0.1d)
                    }),
                BuildPr288Family(
                    "blaster",
                    "Blaster",
                    "normal-firearm",
                    "common",
                    "normal-energy",
                    new[]
                    {
                        new Pr288MarkSource(
                            1, 3,
                            FireSettings.Automatic(7.5d),
                            GunShotPattern.Canonical(1, 2d),
                            1.764d,
                            GunDamageCategory.Energy,
                            0, 0.25d,
                            32d, 32d, 0.1d),
                        new Pr288MarkSource(
                            2, 25,
                            FireSettings.Automatic(7.7250000000000005d),
                            GunShotPattern.Canonical(1, 1.9d),
                            6.089520991780434d,
                            GunDamageCategory.Energy,
                            0, 0.27d,
                            32.96d, 33.6d, 0.1d),
                        new Pr288MarkSource(
                            3, 47,
                            FireSettings.Automatic(7.95d),
                            GunShotPattern.Canonical(1, 1.8d),
                            15.43816236668627d,
                            GunDamageCategory.Energy,
                            1, 0.29d,
                            33.92d, 35.2d, 0.1d)
                    }),
                BuildPr288Family(
                    "arc_rifle",
                    "Arc Rifle",
                    "normal-firearm",
                    "rare",
                    "normal-energy",
                    new[]
                    {
                        new Pr288MarkSource(
                            1, 10,
                            FireSettings.Automatic(7.5d),
                            GunShotPattern.Canonical(1, 2d),
                            3.0170386277171786d,
                            GunDamageCategory.Energy,
                            0, 0.25d,
                            32d, 32d, 0.1d),
                        new Pr288MarkSource(
                            2, 33,
                            FireSettings.Automatic(7.7250000000000005d),
                            GunShotPattern.Canonical(1, 1.9d),
                            7.508095877603602d,
                            GunDamageCategory.Energy,
                            0, 0.27d,
                            32.96d, 33.6d, 0.1d),
                        new Pr288MarkSource(
                            3, 56,
                            FireSettings.Automatic(7.95d),
                            GunShotPattern.Canonical(1, 1.8d),
                            38.36077900641255d,
                            GunDamageCategory.Energy,
                            1, 0.29d,
                            33.92d, 35.2d, 0.1d)
                    }),
                BuildPr288Family(
                    "pulse_shotgun",
                    "Pulse Shotgun",
                    "shotgun",
                    "rare",
                    "shotgun-energy",
                    new[]
                    {
                        new Pr288MarkSource(
                            1, 21,
                            FireSettings.SemiAutomatic(1.45d),
                            GunShotPattern.Canonical(7, 19d),
                            5.005406269401396d,
                            GunDamageCategory.Energy,
                            0, 0.48d,
                            16d, 25d, 0.1d),
                        new Pr288MarkSource(
                            2, 44,
                            FireSettings.SemiAutomatic(1.4935d),
                            GunShotPattern.Canonical(7, 18.05d),
                            13.376290161632655d,
                            GunDamageCategory.Energy,
                            0, 0.5184d,
                            16.48d, 26.25d, 0.1d),
                        new Pr288MarkSource(
                            3, 67,
                            FireSettings.SemiAutomatic(1.537d),
                            GunShotPattern.Canonical(7, 17.1d),
                            35.947092855285135d,
                            GunDamageCategory.Energy,
                            1, 0.5568d,
                            16.96d, 27.500000000000004d, 0.1d)
                    }),
                BuildPr288Family(
                    "inferno_scattergun",
                    "Inferno Scattergun",
                    "shotgun",
                    "rare",
                    "shotgun-thermal",
                    new[]
                    {
                        new Pr288MarkSource(
                            1, 20,
                            FireSettings.SemiAutomatic(1.45d),
                            GunShotPattern.Canonical(7, 19d),
                            3.921866785881265d,
                            GunDamageCategory.Thermal,
                            0, 0.48d,
                            16d, 25d, 0.1d),
                        new Pr288MarkSource(
                            2, 43,
                            FireSettings.SemiAutomatic(1.4935d),
                            GunShotPattern.Canonical(7, 18.05d),
                            15.706993351794498d,
                            GunDamageCategory.Thermal,
                            0, 0.5184d,
                            16.48d, 26.25d, 0.1d),
                        new Pr288MarkSource(
                            3, 66,
                            FireSettings.SemiAutomatic(1.537d),
                            GunShotPattern.Canonical(7, 17.1d),
                            34.0730737964788d,
                            GunDamageCategory.Thermal,
                            1, 0.5568d,
                            16.96d, 27.500000000000004d, 0.1d)
                    }),
                BuildPr288Family(
                    "bio_needler",
                    "Bio-Needler",
                    "normal-firearm",
                    "common",
                    "normal-chemical",
                    new[]
                    {
                        new Pr288MarkSource(
                            1, 6,
                            FireSettings.Automatic(7.5d),
                            GunShotPattern.Canonical(1, 2d),
                            2.0420505000000007d,
                            GunDamageCategory.Chemical,
                            0, 0.25d,
                            32d, 32d, 0.1d),
                        new Pr288MarkSource(
                            2, 29,
                            FireSettings.Automatic(7.7250000000000005d),
                            GunShotPattern.Canonical(1, 1.9d),
                            7.508095877603602d,
                            GunDamageCategory.Chemical,
                            0, 0.27d,
                            32.96d, 33.6d, 0.1d),
                        new Pr288MarkSource(
                            3, 52,
                            FireSettings.Automatic(7.95d),
                            GunShotPattern.Canonical(1, 1.8d),
                            20.177060785713255d,
                            GunDamageCategory.Chemical,
                            1, 0.29d,
                            33.92d, 35.2d, 0.1d)
                    }),
                BuildPr288Family(
                    "corrosive_scattergun",
                    "Corrosive Scattergun",
                    "shotgun",
                    "rare",
                    "shotgun-chemical",
                    new[]
                    {
                        new Pr288MarkSource(
                            1, 22,
                            FireSettings.SemiAutomatic(1.45d),
                            GunShotPattern.Canonical(7, 19d),
                            4.323858131434096d,
                            GunDamageCategory.Chemical,
                            0, 0.48d,
                            16d, 25d, 0.1d),
                        new Pr288MarkSource(
                            2, 45,
                            FireSettings.SemiAutomatic(1.4935d),
                            GunShotPattern.Canonical(7, 18.05d),
                            17.482276275381068d,
                            GunDamageCategory.Chemical,
                            0, 0.5184d,
                            16.48d, 26.25d, 0.1d),
                        new Pr288MarkSource(
                            3, 68,
                            FireSettings.SemiAutomatic(1.537d),
                            GunShotPattern.Canonical(7, 17.1d),
                            37.924182962325816d,
                            GunDamageCategory.Chemical,
                            1, 0.5568d,
                            16.96d, 27.500000000000004d, 0.1d)
                    }),
                BuildPr288Family(
                    "acid_rifle",
                    "Acid Rifle",
                    "normal-firearm",
                    "rare",
                    "normal-chemical",
                    new[]
                    {
                        new Pr288MarkSource(
                            1, 50,
                            FireSettings.Automatic(7.5d),
                            GunShotPattern.Canonical(1, 2d),
                            29.490254833536824d,
                            GunDamageCategory.Chemical,
                            0, 0.25d,
                            32d, 32d, 0.1d),
                        new Pr288MarkSource(
                            2, 73,
                            FireSettings.Automatic(7.7250000000000005d),
                            GunShotPattern.Canonical(1, 1.9d),
                            81.8487164456979d,
                            GunDamageCategory.Chemical,
                            0, 0.27d,
                            32.96d, 33.6d, 0.1d),
                        new Pr288MarkSource(
                            3, 96,
                            FireSettings.Automatic(7.95d),
                            GunShotPattern.Canonical(1, 1.8d),
                            240.6327158456136d,
                            GunDamageCategory.Chemical,
                            1, 0.29d,
                            33.92d, 35.2d, 0.1d)
                    }),
            };
        }

        private sealed class Pr288MarkSource
        {
            public Pr288MarkSource(int mark, int peak, FireSettings fire, GunShotPattern shot, double damage, GunDamageCategory category, int pierce, double knockback, double range, double speed, double radius)
            {
                Mark = mark; Peak = peak; Fire = fire; Shot = shot; Damage = damage; Category = category; Pierce = pierce; Knockback = knockback; Range = range; Speed = speed; Radius = radius;
            }
            public int Mark { get; } public int Peak { get; }
            public FireSettings Fire { get; } public GunShotPattern Shot { get; }
            public double Damage { get; } public GunDamageCategory Category { get; }
            public int Pierce { get; } public double Knockback { get; } public double Range { get; }
            public double Speed { get; } public double Radius { get; }
        }

        private static GunFamily BuildPr288Family(string familyId, string displayName, string category, string rarity, string presentationKey, Pr288MarkSource[] sources)
        {
            StableId rarityId = StableId.Create("gun-rarity", rarity);
            var marks = new GunMark[sources.Length];
            for (int index = 0; index < sources.Length; index++)
            {
                Pr288MarkSource source = sources[index];
                string definitionId = familyId + ".mk" + source.Mark;
                string equipmentValue = "gun-" + familyId + "-mk" + source.Mark;
                ProvisionalCombatProfile combat = new ProvisionalCombatProfile(
                    source.Fire,
                    source.Shot,
                    new GunBaseStats(
                        source.Damage, source.Category, null,
                        PierceValue.FromLegacyInteger(source.Pierce),
                        new RicochetValue(0), 0d,
                        GunAttackDistance.Limited(source.Range), source.Knockback),
                    ShotPattern.Create(
                        GunDeliveryType.Normal,
                        new GunNormalDeliverySettings(source.Speed, source.Radius),
                        null, null, null, null,
                        GunGuidanceSpec.Unguided(),
                        StandardTravellingImpact(), GunEffects.None()),
                    presentationKey);
                Gun blueprint = Gun.CreateAuthored(
                    new GunIdentity(new GunDefinitionId(definitionId), displayName + " MK" + source.Mark, familyId),
                    combat.FireSettings, combat.ShotPattern, combat.BaseStats, combat.Delivery,
                    new GunPresentation(
                        "gun-art." + familyId + ".mk" + source.Mark + ".side-v1",
                        "gun-art." + familyId + ".mk" + source.Mark + ".mounted-top-v1",
                        "gun-delivery-art." + presentationKey + ".v1",
                        "gun-trail-art." + presentationKey + ".v1",
                        "gun-impact-art." + presentationKey + ".v1", null),
                    new GunDropMetadata(
                        StableId.Create("equipment", equipmentValue), rarityId,
                        GunDropAvailability.Live, source.Peak, PlaceholderBaseWeight,
                        GunStrongboxEligibility.FromMinimumTier(1)));
                marks[index] = new GunMark(source.Mark, source.Peak, Math.Min(source.Peak, 100), true, blueprint);
            }
            return new GunFamily(familyId, displayName, StableId.Create("gun-category", category), rarityId, rarity, marks);
        }
    }
}
